### ISSUE TITLE
Bug: project has invalid files names

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [saurabhkpatel/SampleAndroidSlice#1]
It has resources that have uppercase letters:

![image](https://user-images.githubusercontent.com/5357526/45804331-7b1e5f00-bcc4-11e8-932a-6deb8d4469b3.png)

**Comment by saurabhkpatel** [comment]
Thanks for reporting it. 
Updated

**Comment by AndroidDeveloperLB** [comment]
So why close it?
Was it fixed?

**Comment by saurabhkpatel** [comment]
@AndroidDeveloperLB It has been fixed on SEPT 20. Feel free to open it if you're facing the same the issue, Thanks.

**Comment by AndroidDeveloperLB** [comment]
ok thanks
